remove Hosting, remove comments, add Update rpc, fixes #5, fixes #6
seekers-dev/seekers-grpc pull request #7
Opened 2023-06-09 19:51 UTC by Belissimo-T

2023-06-10 08:39 UTC, karl-zschiebsch requested changes

2023-06-10 08:39 UTC, karl-zschiebsch commented on src/main/proto/org/seekers/net/seekers.proto
> +	rpc Ping (Empty) returns (Empty);
Why is the input for ping nothing and returns nothing? A method without input and return, which also calculates nothing, is somehow useless.

2023-06-10 08:39 UTC, karl-zschiebsch commented on src/main/proto/org/seekers/net/seekers.proto
>  	rpc Status (StatusRequest) returns (StatusResponse);
I would like to keep the Status service because it allows users who are not part of the game to see the current state of the game. If we keep it, then the StatusRequest should be empty.

2023-06-10 08:39 UTC, karl-zschiebsch commented on src/main/proto/org/seekers/net/seekers.proto
> -// The Seekers service provides operations related to the Seekers game.
Is there a reason why all these comments were deleted?

2023-06-10 08:39 UTC, karl-zschiebsch commented on src/main/proto/org/seekers/net/seekers.proto
> +message Empty {}
I would change this to an EmptyRequest. A response should not be empty and should at least return some debugging information. This is something I should work on in the future.

2023-06-10 19:08 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	rpc Ping (Empty) returns (Empty);
I forgot to change it, thanks.

2023-06-10 19:09 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> -// The Seekers service provides operations related to the Seekers game.
For my taste a bit too much, I only left in the ones that explain things that are not self-explainatory.

2023-06-10 19:11 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
>  	rpc Status (StatusRequest) returns (StatusResponse);
You are right! Will change that.

2023-06-10 19:13 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +message Empty {}
There is also a [google.protobuf.Empty](https://protobuf.dev/reference/protobuf/google.protobuf/#empty) type. I didn't know if I could use the stdlib of protobuf though. If you will work on in the future, you can then change it in your commit.

2023-06-10 19:19 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	rpc Ping (Empty) returns (Empty);
```suggestion
	rpc Ping (Empty) returns (PingResponse);
```

2023-06-10 19:21 UTC, Belissimo-T reviewed
Thanks for the feedback!

2023-06-10 19:21 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
>  	rpc Status (StatusRequest) returns (StatusResponse);
```suggestion
	rpc Status (Empty) returns (StatusResponse);
```

2023-06-11 13:54 UTC, karl-zschiebsch approved these changes

2023-06-11 13:55 UTC, merged