Change seekers service
seekers-dev/seekers-grpc pull request #9
Opened 2023-06-14 09:03 UTC by karl-zschiebsch

2023-06-15 10:54 UTC, Belissimo-T requested changes

2023-06-15 10:54 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	uint64 seekers_changed = 2;
Why is this count important? Don't you as a sender of the CommandRequest know how many seekers you changed?

2023-06-15 10:54 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	// Timestamp in milliseconds of the time the PingRequest was received.
There is no `PingRequest`, instead it is `Empty`.

```suggestion
	// Timestamp in milliseconds of the time the ping request was received.
```

2023-06-15 10:54 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	uint64 timestamp_ms = 1;
Milliseconds as an integer is to coarse. The time difference will at most be in the single digits. If you want to use an integer, I'd measure it in nanoseconds.

2023-06-16 13:29 UTC, karl-zschiebsch commented on src/main/proto/org/seekers/net/seekers.proto
> +	uint64 timestamp_ms = 1;
I use uint64 because nanos as well as millis are always measured as a whole number in Java. No matter which one we use, it would still be an integer.

2023-06-16 16:12 UTC, Belissimo-T requested changes

2023-06-16 16:12 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	uint64 timestamp_ms = 1;
Lets use nanoseconds [int] then! I would also remove the `_ms` postfix:

```suggestion
	uint64 timestamp = 1;
```

2023-06-16 16:12 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> -	// Timestamp in milliseconds of the time the PingRequest was received.
```suggestion
	// Timestamp in nanoseconds of the time the ping request was received.
```

2023-06-16 16:13 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
> +	uint64 seekers_changed = 2;
Why would the client need that information?

2023-06-16 18:31 UTC, karl-zschiebsch commented on src/main/proto/org/seekers/net/seekers.proto
> +	uint64 seekers_changed = 2;
Simply debugging and testing information, not more.

2023-06-16 18:32 UTC, Belissimo-T requested changes

2023-06-16 18:32 UTC, Belissimo-T commented on src/main/proto/org/seekers/net/seekers.proto
>  	// Timestamp in milliseconds of the time the ping request was received.
```suggestion
	// Timestamp in nanoseconds of the time the ping request was received.
```

2023-06-16 20:13 UTC, Belissimo-T approved these changes

2023-06-16 20:16 UTC, merged